---
# handlers file for loki role

- name: Cleanup temp files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ loki_install_dir }}/Loki/*.log"
    - "{{ loki_install_dir }}/Loki/*.csv"
  listen: "cleanup loki files"

- name: Touch last scan marker file
  ansible.builtin.file:
    path: "{{ loki_install_dir }}/Loki/.last_scan"
    state: touch
    modification_time: preserve
    mode: '0644'
  listen: "touch last scan marker file"
  tags: loki_scan
